#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('tzflow - a git flow productive application', 'by http://torzer.com');

$app->addCommands([
        new \Tzflow\Commands\Info(),
]);

$app->run();