#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

if ( ! function_exists('config')) {
    function config($key, $default = null) {
        if (file_exists('./tzflow.json') === false) {
            $climate = new \League\CLImate\CLImate();

            $climate->br();
            $climate->backgroundRed()->white('File <bold>tzflow.json</bold> not found in this folder !!');
            $climate->yellow('Execute <bold>tzflow init</bold> to create this file.');
            $climate->out('See https://github.com/torzer/tzflow for documentation');
            $climate->br();

            die();
        }
        $config =  new PHLAK\Config\Config('./tzflow.json');

        return $config->get($key, $default);
    }
}

$app = new Application('tzflow - a git flow productive application', 'by http://torzer.com');

$app->addCommands([
        new \Tzflow\Commands\Init(),
        new \Tzflow\Commands\Info(),
        new \Tzflow\Commands\MR(),
        new \Tzflow\Commands\AcceptMR(),
        new \Tzflow\Commands\Run(),
]);

$app->run();